---
variables:
  HOME: /tmp

.create_r10k_yaml: &create_r10k_yaml |
  cat << EOF > /tmp/r10k.yaml
  ---
  cachedir: /etc/puppetlabs/code/cache
  deploy:
    purge_levels: ['puppetfile']
  sources:
    main:
      remote: $CI_PROJECT_DIR
      basedir: /etc/puppetlabs/code/environments
  EOF

.create_puppetdb_conf: &create_puppetdb_conf |
  cat << EOF > /tmp/.puppetlabs/etc/puppet/puppetdb.conf
  [main]
  server_urls = https://puppetdb:8081
  EOF

.create_csr_attributes_yaml: &create_csr_attributes_yaml |
  cat << EOF > /tmp/.puppetlabs/etc/puppet/csr_attributes.yaml
  ---
  custom_attributes:
    1.2.840.113549.1.9.7: 'hashed;$(echo -n "$psk/$(puppet config print certname)//staging" | openssl dgst -binary -sha256 | openssl base64)'
  extension_requests:
    1.3.6.1.4.1.34380.1.3.1: 'catalog'
    1.3.6.1.4.1.34380.1.1.13: ''
    1.3.6.1.4.1.34380.1.1.12: 'staging'
  EOF

.cleanup_cert: &cleanup_cert |
  curl -s -X  DELETE \
  "Accept:application/json" -H "Content-Type: text/pson" \
  --cacert "/tmp/.puppetlabs/etc/puppet/ssl/certs/ca.pem" \
  --cert "/tmp/.puppetlabs/etc/puppet/ssl/certs/$(puppet config print certname).pem" \
  --key "/tmp/.puppetlabs/etc/puppet/ssl/private_keys/$(puppet config print certname).pem" \
  "https://puppetserver:8140/puppet-ca/v1/certificate_status/$(puppet config print certname)?environment=production"

.onceover:
  image: camptocamp/onceover-codequality:latest
  script:
    - 'echo "${CI_COMMIT_REF_NAME}" | grep -q "-" && echo "Do not use - in branch names" && exit 1 || echo "Branch name ok"'
    - 'onceover run codequality  --no_docs'
  interruptible: true

.r10k-deploy:
  image: puppet/r10k:3.1.0
  before_script:
    - test -n "$R10K_BRANCH"
    - test -n "$R10K_ENV"
    - umask 0002
    - ln -s /secrets/.netrc ~/
    - *create_r10k_yaml
    - git fetch --unshallow || echo
    - git fetch origin "${R10K_BRANCH}:${R10K_ENV}"
  script:
    - test -d /etc/puppetlabs/code/environments/${R10K_ENV} || cp -a /etc/puppetlabs/code/environments/staging /etc/puppetlabs/code/environments/${R10K_ENV}
    - r10k deploy --color -c /tmp/r10k.yaml environment ${R10K_ENV} -p --verbose=debug
  after_script:
    - puppet generate types --environment ${R10K_ENV} --environmentpath /etc/puppetlabs/code/environments/
    - puppet module list --tree --environment ${R10K_ENV} --environmentpath /etc/puppetlabs/code/environments/
  # This will work when https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1809 is fixed
  # In the meanwhile, override in your job
  resource_group: r10k/${R10K_ENV}

.g10k-deploy:
  extends: .r10k-deploy
  image: camptocamp/g10k:r10k
  script:
    - g10k -config /tmp/r10k.yaml -branch ${R10K_ENV} -verbose

.r10k-purge:
  image: busybox
  variables:
    GIT_STRATEGY: none
  script:
    - test -n "$R10K_ENV"
    - rm -rf /etc/puppetlabs/code/environments/${R10K_ENV}
  allow_failure: true

.catalog-diff:
  image: camptocamp/puppetserver:6.11.1_locales
  script:
    - echo -e "section_start:`date +%s`:setup\r\e[0KCatalog-diff setup"
    - mkdir -p /tmp/.puppetlabs/etc/puppet
    - *create_puppetdb_conf
    - *create_csr_attributes_yaml
    - puppet ssl submit_request --ca_server puppetserver --certificate_revocation=false
    - echo -e "section_end:`date +%s`:setup\r\e[0K"
    - puppet catalog --environmentpath /etc/puppetlabs/code/environments --environment ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} --certificate_revocation=false diff puppetserver:8140/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} puppetserver:8140/mr_${CI_MERGE_REQUEST_IID} ${DIFF_FLAGS} --output_report /catalog-diff/${REPORT}.json
  after_script:
    - *cleanup_cert
    - echo "You can view the report details at ${PUPPETDIFF_URL}/?report=${REPORT}"
    - 'curl -k -X POST -H "Private-Token: $CI_BOT_TOKEN" -d "body=You can view the Catalog Diff report details at ${PUPPETDIFF_URL}/?report=${REPORT}" $CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes'
  allow_failure: true
  resource_group: catalog-diff
  interruptible: true
  variables:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8


.ghostbuster:
  image: puppet/puppet-agent:6.15.0
  script:
    - apt update
    - apt install -y locales puppetdb-termini git
    - locale-gen en_US.UTF-8
    - *create_puppetdb_conf
    - *create_csr_attributes_yaml
    - puppet ssl submit_request --ca_server puppetserver --certificate_revocation=false
    - gem install specific_install puppetlabs_spec_helper --no-document
    - gem specific_install -l https://github.com/raphink/puppet-lint.git -b file
    - gem specific_install -l https://github.com/camptocamp/puppet-ghostbuster.git
    - rm -f .puppet-lint.rc
    - rake ghostbuster
  after_script:
    - *cleanup_cert
  interruptible: true
  variables:
    HIERA_EYAML_PATH: ./hiera.yaml
